[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/maritaca/*"
  to = "https://chat.maritaca.ai/api/chat/completions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", X-Forwarded-Proto = "https"}

[[redirects]]
  from = "/api/*"
  to = "https://openscriptureapi.org/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", X-Forwarded-Proto = "https"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
